[model]
n_folds = 5
n_iter = 20
random_state = 123
verbose_level = 2

[model.metrics]
scoring = ['roc_auc', 'accuracy', 'precision', 'recall', 'f1']
refit = 'roc_auc'

[model.data]
num_samples = 1000
num_features = 10
num_classes = 2
target_col = "y"
test_size = 0.2
